from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from dating_boost import __version__
from dating_boost.core.production_store import (
    BACKUP_RECOVERY_KEY_SCHEMA_VERSION,
    DIAGNOSTIC_BUNDLE_SCHEMA_VERSION,
    ENCRYPTED_PAYLOAD_SCHEMA_VERSION,
    KEYCHAIN_BINDING_SCHEMA_VERSION,
    RELEASE_MANIFEST_SCHEMA_VERSION,
)
from dating_boost.core.production_store import ProductionDataStore
from dating_boost.core.gui_harness import GUI_HARNESS_SCHEMA_VERSION
from dating_boost.core.support import SUPPORT_EVIDENCE_SCHEMA_VERSION, SUPPORT_LOG_SCHEMA_VERSION


CAPABILITIES_SCHEMA_VERSION = 1

SCHEMA_VERSIONS: dict[str, int] = {
    "capabilities": 1,
    "user_profile": 1,
    "user_disclosure_profile": 1,
    "user_readiness": 1,
    "app_observation": 1,
    "match_index": 1,
    "context_pack": 1,
    "content_policy": 1,
    "action_policy": 1,
    "feedback_event": 1,
    "action_result": 1,
    "reply_draft": 2,
    "workflow_result": 1,
    "scan_batch": 1,
    "automation_authorization": 1,
    "automation_state": 1,
    "automation_session": 1,
    "operator_session": 1,
    "operator_work_item": 1,
    "operator_work_queue": 1,
    "appointment_ledger": 1,
    "progress_report": 1,
    "skill_package": 1,
    "planner_assessment": 1,
    "goal_plan": 1,
    "planner_recommendation": 1,
    "observation_authoring": 1,
    "conversation_eval": 1,
    "replay_timeline": 1,
    "app_profile": 1,
    "data_store": 2,
    "migration": 1,
    "automation_lock": 1,
    "confirmation": 1,
    "production_smoke": 1,
    "gui_harness": GUI_HARNESS_SCHEMA_VERSION,
    "encrypted_payload": ENCRYPTED_PAYLOAD_SCHEMA_VERSION,
    "keychain_binding": KEYCHAIN_BINDING_SCHEMA_VERSION,
    "backup_recovery_key": BACKUP_RECOVERY_KEY_SCHEMA_VERSION,
    "daemon_state": 1,
    "daemon_event": 1,
    "daemon_job": 1,
    "diagnostic_bundle": DIAGNOSTIC_BUNDLE_SCHEMA_VERSION,
    "support_log": SUPPORT_LOG_SCHEMA_VERSION,
    "support_evidence": SUPPORT_EVIDENCE_SCHEMA_VERSION,
    "release_manifest": RELEASE_MANIFEST_SCHEMA_VERSION,
}

SUPPORTED_COMMANDS: list[str] = [
    "capabilities",
    "adapter codex install",
    "adapter codex doctor",
    "adapter claude-code install",
    "adapter claude-code doctor",
    "adapter openclaw install",
    "adapter openclaw doctor",
    "adapter hermes install",
    "adapter hermes doctor",
    "init-profile",
    "import-observation",
    "observe-screenshot",
    "observation template",
    "observation validate",
    "observation normalize",
    "draft",
    "feedback",
    "authorize",
    "user interview template",
    "user ingest-profile",
    "user ingest-interview",
    "user disclosure-profile",
    "user readiness",
    "memory ingest-observation",
    "memory get-match",
    "context build",
    "policy check-draft",
    "policy check-action",
    "action record-result",
    "feedback record",
    "workflow draft",
    "skill doctor",
    "planner update",
    "planner get",
    "planner recommend",
    "planner event-log",
    "automation scan template",
    "automation scan validate",
    "automation scan normalize",
    "automation scan assemble",
    "automation session start",
    "automation session step",
    "automation session stop",
    "automation report latest",
    "automation get-state",
    "automation pause",
    "automation resume",
    "automation record-authorization",
    "automation availability set",
    "automation goal set",
    "operator session start",
    "operator next",
    "operator ingest-observation",
    "operator record-action-result",
    "operator stop",
    "operator report latest",
    "operator get-state",
    "eval run",
    "replay latest",
    "data doctor",
    "data migrate",
    "data export",
    "data delete",
    "data unlock",
    "data lock",
    "data rekey",
    "data backup",
    "data restore",
    "safety pause",
    "safety resume",
    "safety status",
    "daemon run",
    "daemon install",
    "daemon uninstall",
    "daemon status",
    "daemon stop",
    "diagnostics doctor",
    "diagnostics bundle",
    "support session start",
    "support session stop",
    "support record-event",
    "support bundle",
    "harness doctor",
    "harness screenshot",
    "harness tinder launch",
    "harness tinder open-profile",
    "harness tinder observe",
    "harness tinder action",
    "harness tinder workflow",
    "harness tinder send-message",
    "harness wechat launch",
    "harness wechat observe",
    "harness wechat stage-draft",
    "harness wechat send-message",
    "release doctor",
    "confirmation create",
    "confirmation confirm",
    "confirmation validate",
]


def build_capabilities(data_dir: Path | None = None) -> dict[str, Any]:
    storage_status = _storage_status(data_dir)
    return {
        "schema_version": CAPABILITIES_SCHEMA_VERSION,
        "tool_version": __version__,
        "git_commit": _git_commit(),
        "schema_versions": dict(SCHEMA_VERSIONS),
        "supported_commands": list(SUPPORTED_COMMANDS),
        "data_dir": str(data_dir.resolve()) if data_dir is not None else None,
        "storage_capabilities": {
            "sqlite": True,
            "storage_backend": storage_status["storage_backend"],
            "canonical_store": "sqlite",
            "encrypted_default": True,
            "keychain": True,
            "encrypted_payload_schema_version": ENCRYPTED_PAYLOAD_SCHEMA_VERSION,
            "json_host_work_dir_contract": True,
            "data_doctor": True,
            "migration": True,
            "backup": True,
            "restore": True,
            "rekey": True,
            "backup_recovery_key_schema_version": BACKUP_RECOVERY_KEY_SCHEMA_VERSION,
            "backup_requires_recovery_passphrase": True,
            "backup_recovery_passphrase_sources": ["env", "file"],
        },
        "policy_capabilities": {
            "action_authorization": True,
            "draft_content_check": True,
            "blocked_draft_redaction": True,
            "high_risk_autonomous_switch": True,
            "confirmation_contract": True,
            "global_kill_switch": True,
        },
        "memory_capabilities": {
            "user_profile": True,
            "user_disclosure_profile": True,
            "user_readiness": True,
            "match_identity_index": True,
            "observation_ingest": True,
            "context_pack_build": True,
            "feedback_events": True,
            "export": True,
            "delete": True,
        },
        "agent_native_capabilities": {
            "host_agent_adapters": ["codex", "claude_code", "openclaw", "hermes"],
            "codex_skill": True,
            "claude_code_adapter": True,
            "openclaw_adapter": True,
            "hermes_openclaw_compatible_adapter": True,
            "host_executed_action_audit": True,
            "workflow_draft_runner": True,
            "automation_session": True,
            "operator_session": True,
            "goal_oriented_operator": True,
            "host_loop_supervisor": True,
            "host_loop_recovery": True,
            "host_loop_doctor": True,
            "host_loop_init": True,
            "host_loop_resume": True,
            "tinder_host_loop": True,
            "wechat_host_loop": True,
            "host_loop_command": "dating-boost-host-loop",
            "supported_app_profiles": ["tinder", "wechat"],
            "host_loop_app_profiles": ["tinder", "wechat"],
            "multi_app_profiles": True,
            "observation_authoring": True,
            "conversation_eval": True,
            "replay_timeline": True,
            "automation_dry_run_default": True,
            "automation_external_scheduler": True,
            "appointment_ledger": True,
            "progress_report": True,
            "skill_doctor": True,
            "scan_authoring": True,
            "github_skill_installable": True,
            "post_action_verification_required": True,
            "goal_oriented_planning": True,
            "conversation_scores": True,
            "topic_lifecycle": True,
            "soft_invite_probe": True,
            "planner_report": True,
            "self_disclosure_profile": True,
            "autonomous_requires_user_profile": True,
            "low_investment_repair": True,
            "reciprocity_tracking": True,
            "production_smoke": True,
            "real_stage_smoke_required": True,
            "local_daemon": True,
            "launchd_install": True,
            "live_send_supported": True,
            "stage_gui_harness": True,
            "managed_gui_send": True,
            "managed_gui_send_default": False,
            "iphone_mirroring_harness": True,
            "tinder_gui_launch": True,
            "tinder_gui_navigation": True,
            "native_gui_profile_navigation": True,
            "tinder_profile_read_harness": True,
            "tinder_chat_navigation_harness": True,
            "tinder_live_send_harness": True,
            "wechat_macos_harness": True,
            "wechat_gui_launch": True,
            "wechat_chat_observation_harness": True,
            "wechat_draft_stage_harness": True,
            "wechat_live_send_harness": True,
            "ci_tested_version": __version__,
            "data_doctor": True,
            "capability_mismatch_blocks_startup": True,
            "dirty_source_warning": True,
            "llm_owned_by_host_agent": True,
            "live_gui_harness": False,
            "mcp_adapter": False,
        },
        "diagnostic_capabilities": {
            "local_redacted_bundle": True,
            "support_log": True,
            "encrypted_evidence_vault": True,
            "support_bundle_redactions": ["strict", "standard", "full-with-consent"],
            "topic_provenance": True,
            "clipboard_fingerprint": True,
            "sensitive_export_requires_confirm_token": True,
            "network_telemetry": False,
        },
        "release_capabilities": {
            "pypi": True,
            "github_release": True,
            "skill_package": True,
            "claude_code_adapter": True,
            "openclaw_adapter": True,
            "hermes_openclaw_compatible_adapter": True,
        },
        "warnings": [
            "Agent-native mode can expose visible dating app content to the host agent.",
            "High-risk actions remain disabled unless the user explicitly enables autonomous handling.",
        ],
    }


def _git_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return result.stdout.strip() or "unknown"


def _storage_status(data_dir: Path | None) -> dict[str, str]:
    if data_dir is None:
        return {"storage_backend": "sqlite"}
    try:
        doctor = ProductionDataStore(data_dir).doctor()
    except Exception:  # noqa: BLE001 - capabilities must remain diagnostic-only.
        return {"storage_backend": "unknown"}
    return {"storage_backend": str(doctor.get("storage_backend") or "unknown")}
